### ISSUE TITLE
Some questions about musje

### ISSUE THREAD

**Issue by watersoft123** [malcomwu/musje#1]
Hi malcomwu. 
I have some questions when I use musje:
1.How to punctuate the lyrics？
2.How to set the number of beats per minute and reflect it during playback？
3.How to pause(not stop) or loop the playing? 
4.How to set the pitch of a song？

Thank you first.

**Comment by malcomwu** [comment]
Hi watersoft123,
Thank you for your questions.
1. It is possible to punctuate the lyrics such as: isn't it? Hello, how are you?
2. The tempo is not implemented yet. My problem is how to do the notation so that this functionality is not in yet. Such as `1 = 120`, `d = 120` or `tempo = 120`.
3. The player is raw. I still don't know how to do it right yet.
4. The pitch is in `1 = C`. I don't know how to name it, in key or transpose yet.
