### ISSUE TITLE
how to calculating the duration of a track

### ISSUE THREAD

**Issue by alexnest** [malcomwu/musje#2]
Hi malcomwu.

Can you provide a method for calculating the duration of a track? I want to do something when the music is finished and i check the open comment it seems that hard to use svg describe the bmp( the number of beats per minute), I consider that the easyest way is set the song total time in my app.

**Comment by malcomwu** [comment]
Hi alexnest,

The duration of a track (i.e., staff in the notation) is not calculated directly because it depends on the player for some repeat, tempo, fermata, grace or other notations which may affect it.

The current player is preliminary and rough. The timing information for each music data can be found in `score.body.parts[0].staves[0].cells[c].data[d].t` in which c is the measure index and d the music data index. So find the last measure and the last music data (`lmd`) for a staff; then, `lmd.t` plus possible `lmd.duration.seconds` is what you want.

**Comment by alexnest** [comment]
Thx a lot.I will try it in my app.
